### ISSUE TITLE
Drupal page update needed?

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#1]
The Drupal/Tripal documentation at
    https://www.drupal.org/node/2789913/git-instructions/7.x-1.x/nonmaintainer

may need updating to point to https://github.com/tripal/brapi? Perhaps a review of all the existing BrAPI doc URLs(?) e.g. https://brapi.docs.apiary.io/

**Comment by guignonv** [comment]
Unfortunately, the page your are pointing is auto-generated and therefore cant' be edited!
But this is not a big deal because I will maintain both git synchronized. Drupal.org will keep holding official releases while github version is here to facilitate code collaboration (as asked by some people of the Tripal community).

**Comment by RichardBruskiewich** [comment]
The joy of automation! I assume that you are allowed to post your own customized text for at least a part of the site. You might simply emphasise the "new" location of the code, right up on the front page, and declare the Drupal autogenerated pages as "deprecated". That may help avoid a little bit of confusion for Tripal BrAPI neophytes (like me, LOL)
